#!/usr/bin/env bash

# See https://github.com/edr3x/tmux-sessionizer

session=$(find ~ ~/.config ~/dev ~/obsidian -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
  tmux split-window -h -t "$session_name" -c "$session"
  tmux split-window -v -t "$session_name" -c "$session"
fi

tmux switch-client -t "$session_name"
